dec0= 0.
;latitude= 18.
;function parangle, ha, dec, latitude, DEGREE=degree

;function pangle, az, za, modno

ha=0.5*findgen(48)- 12.
dec=fltarr(48)+ dec0
latitude= 18.353944

eqtoaoaz, ha, dec, az, za, 1

parang0 = pangle( az, za)
parang1= parangle( ha, dec, latitude)

ver,-180,180
hor, -12, 12 

plot, ha, parang0
oplot, ha, parang1, col=!red, lines=2
oplot, [0,0],[-1,1]*400, lines=2

