#! /usr/bin/env python
'''This script is started by start_dishserver and runs on a RPI
whose serial port is connected to the drive encoders for the
UGRadio Interferometer.'''

from __future__ import print_function
import time
import traceback
import os

EAST = '/home/ugastro/east'
WEST = '/home/ugastro/west'

if os.path.exists(EAST):
    from ugradio.interf import TelescopeServerEast as TelescopeServer
elif os.path.exists(WEST):
    from ugradio.interf import TelescopeServerWest as TelescopeServer
else:
    raise RuntimeError('No east/west file found in home directory.')

while True:
    try:
        print('Starting server...')
        ts = TelescopeServer()
        ts.run(verbose=True)
    except Exception as e:
        print('Dish server crashed with the following message:')
        print(traceback.format_exc())
        print('Restarting...')
        time.sleep(1)

