PRO SET_MPI, IP_ADDR, PORT, MOVE_AXIS, VERBOSE=VERBOSE

ARG=STRING(13B)+STRING(13B)+MOVE_AXIS+'MPI'+STRING(13B)
IF VERBOSE EQ 1 THEN PRINT, 'Setting Drive ',MOVE_AXIS,' mode to Incremental Positioning.'
OEM_REPLY='1234567'

WAIT,1

SOCKET,SOCK_UNIT,IP_ADDR,PORT,/GET_LUN
WRITEU,SOCK_UNIT,ARG
READU,SOCK_UNIT,OEM_REPLY
CLOSE,SOCK_UNIT
FREE_LUN,SOCK_UNIT

END
