PRO DRIVE_OFF, IP_ADDR, PORT, VERBOSE=VERBOSE

ARG=STRING(13B)+STRING(13B)+'OFF'+STRING(13B)
IF VERBOSE EQ 1 THEN PRINT, 'Deenergizing Drives'
OEM_REPLY='12345'

WAIT,1

SOCKET,SOCK_UNIT,IP_ADDR,PORT,/GET_LUN
WRITEU,SOCK_UNIT,ARG
READU,SOCK_UNIT,OEM_REPLY
CLOSE,SOCK_UNIT
FREE_LUN,SOCK_UNIT

END
