


;;for nr=0,3 do s[*,nr] = (nr+1)*s[*,nr]
;ss = transpose(s) ## s
;print, ss
;ssi = invert(ss)
;;stop

s = fltarr(3,4)
n=4
m=3

time = [5,7,9,11]
;time=time-8.
s[0,*]=1.
s[1,*]=time
s[2,*]=time^2
t=[142,168,211,251]

s = double(s)/ sqrt(20.d0)
t = double(t)/ sqrt(20.d0)

ss=transpose(s)##s
st = transpose(s)##t
ssi = invert(ss)
a = ssi ## st
bt = s ## a
sigsq = total((t - bt)^2)/(n-m)
dc =  ssi[ (m+1) * indgen(m)]
sigdcsq = sigsq * dc
sigdc = sqrt(sigdcsq)
ncov = ssi/sqrt(dc # dc)

;WE ASSUMING SIGMA_DATA  = 1. THEREFORE, CHISQ IS ...

chisq = total( (t-bt)^2)

STOP

;WEIGHTING:
s3 = 1./(1.*sqrt(sigsq))
;s3 = 1./3.
wgt = fltarr(4)
wgt[0] = s3
wgt[1] = s3
wgt[2] = s3
wgt[3] = s3

;wgt=fltarr(4) + 1.
;wgt[1]=3.

s_x=fltarr(3,4)
for nr=0,3 do s_x[*,nr] = wgt[nr]*s[*,nr]
t_x=wgt * t
ss_x=transpose(s_x)##s_x
st_x = transpose(s_x)##t_x
ssi_x = invert(ss_x)
a_x = ssi_x ## st_x

;CALCULATE RESIDUALS FROM WEIGHTED EQUATIONS...
bt_x_x = s_x ## a_x
sigsq_x_x = total((t_x - bt_x_x)^2)/(n-m)
chisq = sigsq_x_x

bt_x = bt_x_x
sigsq_x = sigsq_x_x

;;CALCULATE RESIDUALS FROM UNWEIGHTED EQUATIONS...
;bt_x = s ## a_x
;sigsq_x = total((t - bt_x)^2)/(n-m)

dc_x =  ssi_x[ (m+1) * indgen(m)]
sigdcsq_x = sqrt(CHISQ * dc_x)
ncov_x = ssi_x/sqrt(dc_x # dc_x)

stop




print, a
print, sigdcsq
print, sigsq

n=3
m=2
s = fltarr(m,n)
s[0,*]=1.
s[1,*]=[2.,3.,4.]
t= [5.1,6.9,9.1]

ss=transpose(s)##s
st = transpose(s)##t
ssi = invert(ss)
a = ssi ## st
bt = s ## a
sigsq = total((t - bt)^2)/(n-m)
dc =  ssi[ (m+1) * indgen(m)]
sigdcsq = sqrt(sigsq * dc)
ncov = ssi/sqrt(dc # dc)

s3 = 1./(1.*sqrt(sigsq))
wgt = fltarr(n) + s3
;wgt[0] = s3
;wgt[1] = s3
;wgt[2] = s3

s_x=0l*s
for nr=0,2 do s_x[*,nr] = wgt[nr]*s[*,nr]
t_x=wgt * t
ss_x=transpose(s_x)##s_x
st_x = transpose(s_x)##t_x
ssi_x = invert(ss_x)
a_x = ssi_x ## st_x

;CALCULATE RESIDUALS FROM WEIGHTED EQUATIONS...
bt_x_x = s_x ## a_x
sigsq_x_x = total((t_x - bt_x_x)^2)/(n-m)
chisq = sigsq_x_x

dc_x =  ssi_x[ (m+1) * indgen(m)]
sigdcsq_x = sqrt(chisq * dc_x)
ncov_x = ssi_x/sqrt(dc_x # dc_x)

print, transpose(a) ## ss ## a
print, transpose(a) ## ss_x ## a

print, transpose(a) ## ssi ## a
print, transpose(a) ## ssi_x ## a


stop


