fsmpl= 1

nsmpl= 256   ;*16
tsmpl= (findgen(nsmpl)- nsmpl/2)/fsmpl

fsig= 0.1* fsmpl
;fsig=70.5*fsmpl

et= cos( 2.*!pi* fsig* tsmpl)
plot, tsmpl, et, psym=-4


fout= fsmpl* (findgen(nsmpl)- nsmpl/2)/nsmpl

dft, tsmpl, et, fout, ef

plot, fout, abs(ef)
