fit[ nrdish].sigma[zron]= sigma
fit[ nrdish].problem[zron]= problem
fit[ nrdish].zro1[zron]= zro1
fit[ nrdish].hgt1[zron]= hgt1
fit[ nrdish].cen1[zron]= cen1
fit[ nrdish].wid1[zron]= wid1

fit[ nrdish].sigzro1[zron]= sigzro1
fit[ nrdish].sighgt1[zron]= sighgt1
fit[ nrdish].sigcen1[zron]= sigcen1
fit[ nrdish].sigwid1[zron]= sigwid1

fit[ nrdish].dishaz[ zron]= dishaz
fit[ nrdish].dishalt[ zron]= dishalt

