;window,2,xs=300,ys=225

retall

;define dirname as the directory in which the files exist. 

;dirname= '/home/heiles/dzd2/courses/ay121/data/tstdata/'
dirname= '/home/goldston/interfer_point/'

file= $
;['Wed_Apr__9_12:14:41_2003_scanfit.sav', $
;'Wed_Apr__9_12:18:14_2003_scanfit.sav', $

['Wed_Apr__9_12:49:54_2003_scanfit.sav', $
'Wed_Apr__9_12:51:42_2003_scanfit.sav', $
'Wed_Apr__9_12:53:27_2003_scanfit.sav', $
'Wed_Apr__9_12:55:12_2003_scanfit.sav', $
'Wed_Apr__9_12:56:58_2003_scanfit.sav', $
'Wed_Apr__9_12:59:26_2003_scanfit.sav', $
'Wed_Apr__9_13:01:14_2003_scanfit.sav', $
'Wed_Apr__9_13:02:58_2003_scanfit.sav', $
'Wed_Apr__9_13:04:43_2003_scanfit.sav', $
'Wed_Apr__9_13:06:27_2003_scanfit.sav', $
'Wed_Apr__9_13:08:12_2003_scanfit.sav', $
'Wed_Apr__9_13:10:00_2003_scanfit.sav', $
'Wed_Apr__9_13:11:47_2003_scanfit.sav', $
'Wed_Apr__9_13:13:33_2003_scanfit.sav', $
'Wed_Apr__9_13:15:19_2003_scanfit.sav', $
'Wed_Apr__9_13:17:04_2003_scanfit.sav', $
'Wed_Apr__9_13:18:52_2003_scanfit.sav', $
'Wed_Apr__9_13:20:40_2003_scanfit.sav', $
'Wed_Apr__9_13:22:28_2003_scanfit.sav', $
'Wed_Apr__9_13:24:15_2003_scanfit.sav', $
'Wed_Apr__9_13:26:02_2003_scanfit.sav', $
'Wed_Apr__9_13:27:49_2003_scanfit.sav', $
'Wed_Apr__9_13:29:37_2003_scanfit.sav', $
'Wed_Apr__9_13:31:24_2003_scanfit.sav', $
'Wed_Apr__9_13:33:12_2003_scanfit.sav', $
'Wed_Apr__9_13:35:01_2003_scanfit.sav', $
'Wed_Apr__9_13:36:47_2003_scanfit.sav', $
'Wed_Apr__9_13:38:33_2003_scanfit.sav', $
'Wed_Apr__9_13:40:20_2003_scanfit.sav', $
'Wed_Apr__9_13:42:06_2003_scanfit.sav', $
'Wed_Apr__9_13:43:53_2003_scanfit.sav', $
'Wed_Apr__9_13:45:39_2003_scanfit.sav', $
'Wed_Apr__9_13:47:27_2003_scanfit.sav', $
'Wed_Apr__9_13:49:13_2003_scanfit.sav', $
'Wed_Apr__9_13:51:00_2003_scanfit.sav', $
'Wed_Apr__9_13:52:46_2003_scanfit.sav', $
'Wed_Apr__9_13:54:33_2003_scanfit.sav', $
'Wed_Apr__9_13:56:19_2003_scanfit.sav', $
'Wed_Apr__9_13:58:06_2003_scanfit.sav', $
'Wed_Apr__9_14:00:37_2003_scanfit.sav', $
'Wed_Apr__9_14:02:27_2003_scanfit.sav', $
'Wed_Apr__9_14:04:14_2003_scanfit.sav', $
'Wed_Apr__9_14:06:00_2003_scanfit.sav', $
'Wed_Apr__9_14:07:46_2003_scanfit.sav', $
'Wed_Apr__9_14:09:31_2003_scanfit.sav', $
'Wed_Apr__9_14:11:17_2003_scanfit.sav', $
'Wed_Apr__9_14:13:03_2003_scanfit.sav', $
'Wed_Apr__9_14:14:49_2003_scanfit.sav', $
'Wed_Apr__9_14:16:38_2003_scanfit.sav', $
'Wed_Apr__9_14:18:24_2003_scanfit.sav', $
'Wed_Apr__9_14:20:10_2003_scanfit.sav', $
'Wed_Apr__9_14:21:57_2003_scanfit.sav', $
'Wed_Apr__9_14:23:42_2003_scanfit.sav', $
'Wed_Apr__9_14:25:28_2003_scanfit.sav', $
'Wed_Apr__9_14:27:15_2003_scanfit.sav', $
'Wed_Apr__9_14:29:02_2003_scanfit.sav', $
'Wed_Apr__9_14:30:48_2003_scanfit.sav', $
'Wed_Apr__9_14:32:33_2003_scanfit.sav', $
'Wed_Apr__9_14:34:21_2003_scanfit.sav', $
'Wed_Apr__9_14:36:07_2003_scanfit.sav', $
'Wed_Apr__9_14:37:59_2003_scanfit.sav', $
'Wed_Apr__9_14:39:49_2003_scanfit.sav', $
'Wed_Apr__9_14:41:38_2003_scanfit.sav', $
'Wed_Apr__9_14:43:28_2003_scanfit.sav', $
'Wed_Apr__9_14:45:18_2003_scanfit.sav', $
'Wed_Apr__9_14:47:20_2003_scanfit.sav', $
'Wed_Apr__9_14:49:05_2003_scanfit.sav', $
'Wed_Apr__9_14:50:50_2003_scanfit.sav', $
'Wed_Apr__9_14:52:34_2003_scanfit.sav', $
'Wed_Apr__9_14:54:19_2003_scanfit.sav', $
'Wed_Apr__9_14:56:04_2003_scanfit.sav', $
'Wed_Apr__9_14:57:51_2003_scanfit.sav', $
'Wed_Apr__9_15:00:21_2003_scanfit.sav', $
'Wed_Apr__9_15:02:10_2003_scanfit.sav', $
'Wed_Apr__9_15:03:54_2003_scanfit.sav', $
'Wed_Apr__9_15:05:39_2003_scanfit.sav', $
'Wed_Apr__9_15:07:24_2003_scanfit.sav', $
'Wed_Apr__9_15:09:09_2003_scanfit.sav', $
'Wed_Apr__9_15:10:54_2003_scanfit.sav', $
'Wed_Apr__9_15:12:39_2003_scanfit.sav', $
'Wed_Apr__9_15:14:24_2003_scanfit.sav', $
'Wed_Apr__9_15:16:10_2003_scanfit.sav', $
'Wed_Apr__9_15:17:56_2003_scanfit.sav', $
'Wed_Apr__9_15:19:42_2003_scanfit.sav', $
'Wed_Apr__9_15:21:26_2003_scanfit.sav', $ 
'Wed_Apr__9_15:23:12_2003_scanfit.sav', $
'Wed_Apr__9_15:24:58_2003_scanfit.sav', $
'Wed_Apr__9_15:26:44_2003_scanfit.sav', $
'Wed_Apr__9_15:28:30_2003_scanfit.sav', $
'Wed_Apr__9_15:30:15_2003_scanfit.sav', $
'Wed_Apr__9_15:32:03_2003_scanfit.sav', $
'Wed_Apr__9_15:33:51_2003_scanfit.sav', $
'Wed_Apr__9_15:35:37_2003_scanfit.sav', $
'Wed_Apr__9_15:37:26_2003_scanfit.sav', $
'Wed_Apr__9_15:39:13_2003_scanfit.sav', $
'Wed_Apr__9_15:40:59_2003_scanfit.sav', $

;'Wed_Apr__9_15:46:49_2003_scanfit.sav', $
;'Wed_Apr__9_15:48:41_2003_scanfit.sav', $
;'Wed_Apr__9_15:50:27_2003_scanfit.sav', $
;'Wed_Apr__9_15:52:14_2003_scanfit.sav', $
;'Wed_Apr__9_15:54:00_2003_scanfit.sav', $
;'Wed_Apr__9_15:55:47_2003_scanfit.sav', $

'Wed_Apr__9_15:57:34_2003_scanfit.sav', $
'Wed_Apr__9_16:00:04_2003_scanfit.sav', $
'Wed_Apr__9_16:01:55_2003_scanfit.sav', $
'Wed_Apr__9_16:03:40_2003_scanfit.sav', $
'Wed_Apr__9_16:05:24_2003_scanfit.sav', $
'Wed_Apr__9_16:07:08_2003_scanfit.sav', $
'Wed_Apr__9_16:08:53_2003_scanfit.sav', $
'Wed_Apr__9_16:10:37_2003_scanfit.sav', $
'Wed_Apr__9_16:12:22_2003_scanfit.sav', $
'Wed_Apr__9_16:14:10_2003_scanfit.sav', $
'Wed_Apr__9_16:15:57_2003_scanfit.sav', $
'Wed_Apr__9_16:17:43_2003_scanfit.sav', $
'Wed_Apr__9_16:19:29_2003_scanfit.sav', $
'Wed_Apr__9_16:21:13_2003_scanfit.sav', $
'Wed_Apr__9_16:23:00_2003_scanfit.sav', $
'Wed_Apr__9_16:24:46_2003_scanfit.sav', $
'Wed_Apr__9_16:26:30_2003_scanfit.sav', $
'Wed_Apr__9_16:28:14_2003_scanfit.sav', $
'Wed_Apr__9_16:30:02_2003_scanfit.sav', $
'Wed_Apr__9_16:31:47_2003_scanfit.sav', $
'Wed_Apr__9_16:33:32_2003_scanfit.sav', $
'Wed_Apr__9_16:35:17_2003_scanfit.sav', $
'Wed_Apr__9_16:37:03_2003_scanfit.sav', $
'Wed_Apr__9_16:38:49_2003_scanfit.sav', $
'Wed_Apr__9_16:40:39_2003_scanfit.sav', $
'Wed_Apr__9_16:42:25_2003_scanfit.sav', $
'Wed_Apr__9_16:44:12_2003_scanfit.sav', $
'Wed_Apr__9_16:45:59_2003_scanfit.sav', $
'Wed_Apr__9_16:47:46_2003_scanfit.sav', $
'Wed_Apr__9_16:49:33_2003_scanfit.sav', $
'Wed_Apr__9_16:51:21_2003_scanfit.sav', $
'Wed_Apr__9_16:53:10_2003_scanfit.sav', $
'Wed_Apr__9_16:54:59_2003_scanfit.sav', $
'Wed_Apr__9_16:56:46_2003_scanfit.sav', $
'Wed_Apr__9_16:59:21_2003_scanfit.sav', $
'Wed_Apr__9_17:01:12_2003_scanfit.sav', $
'Wed_Apr__9_17:02:57_2003_scanfit.sav', $
'Wed_Apr__9_17:04:41_2003_scanfit.sav', $
'Wed_Apr__9_17:06:25_2003_scanfit.sav', $
'Wed_Apr__9_17:08:09_2003_scanfit.sav', $
'Wed_Apr__9_17:09:53_2003_scanfit.sav', $
'Wed_Apr__9_17:11:37_2003_scanfit.sav', $
'Wed_Apr__9_17:13:21_2003_scanfit.sav', $
'Wed_Apr__9_17:15:06_2003_scanfit.sav', $
'Wed_Apr__9_17:16:50_2003_scanfit.sav', $
'Wed_Apr__9_17:18:37_2003_scanfit.sav', $
'Wed_Apr__9_17:20:21_2003_scanfit.sav', $
'Wed_Apr__9_17:22:05_2003_scanfit.sav', $
'Wed_Apr__9_17:23:50_2003_scanfit.sav', $
'Wed_Apr__9_17:25:35_2003_scanfit.sav', $
'Wed_Apr__9_17:27:19_2003_scanfit.sav', $
'Wed_Apr__9_17:29:02_2003_scanfit.sav', $
'Wed_Apr__9_17:30:46_2003_scanfit.sav', $
'Wed_Apr__9_17:32:30_2003_scanfit.sav', $
'Wed_Apr__9_17:34:14_2003_scanfit.sav', $
'Wed_Apr__9_17:35:58_2003_scanfit.sav', $
'Wed_Apr__9_17:37:42_2003_scanfit.sav', $
'Wed_Apr__9_17:39:28_2003_scanfit.sav', $
'Wed_Apr__9_17:41:12_2003_scanfit.sav', $
'Wed_Apr__9_17:42:56_2003_scanfit.sav', $
'Wed_Apr__9_17:44:40_2003_scanfit.sav', $
'Wed_Apr__9_17:46:25_2003_scanfit.sav', $
'Wed_Apr__9_17:48:09_2003_scanfit.sav', $
'Wed_Apr__9_17:49:54_2003_scanfit.sav', $
'Wed_Apr__9_17:51:39_2003_scanfit.sav', $

'Wed_Apr__9_17:53:26_2003_scanfit.sav', $
'Wed_Apr__9_17:55:12_2003_scanfit.sav', $
'Wed_Apr__9_17:56:58_2003_scanfit.sav', $
'Wed_Apr__9_17:59:29_2003_scanfit.sav', $
'Wed_Apr__9_18:01:21_2003_scanfit.sav', $
'Wed_Apr__9_18:03:05_2003_scanfit.sav', $
'Wed_Apr__9_18:04:49_2003_scanfit.sav', $
'Wed_Apr__9_18:06:35_2003_scanfit.sav', $
'Wed_Apr__9_18:08:20_2003_scanfit.sav', $
'Wed_Apr__9_18:10:05_2003_scanfit.sav', $
'Wed_Apr__9_18:11:52_2003_scanfit.sav', $
'Wed_Apr__9_18:13:37_2003_scanfit.sav', $
'Wed_Apr__9_18:15:22_2003_scanfit.sav', $
'Wed_Apr__9_18:17:08_2003_scanfit.sav', $
'Wed_Apr__9_18:18:52_2003_scanfit.sav']

;'Wed_Apr__9_17:51:39_2003_scanfit.sav', $
;'Wed_Apr__9_17:53:26_2003_scanfit.sav', $
;'Wed_Apr__9_17:55:12_2003_scanfit.sav', $
;'Wed_Apr__9_17:56:58_2003_scanfit.sav']  

nrfiles= n_elements( file)
outfile= file

FOR NR= 0, NRFILES-1 DO BEGIN &$
loc= strpos( file[nr], 'scan') &$
outfile[ nr]= strmid( file[nr],0,loc+4) + strmid( file[nr], loc+4) &$
ENDFOR

file=outfile

loc= strpos( file[ 0], 'scan') &$
coeffsfile= strmid( file[ 0], 0, loc) + 'coeffs' + strmid( file[ 0], loc+7)


;DEFINE THE STRUCTURE CONTAINING THE DERIVED COEFFS; FOLLOW THE SAME
;ORGANIZATIONAL STRUCTURE AS THE ORIGINAL DATA...
COEFFS = replicate ( { $
	azsigma:    	0.0       , $ ; azsigma of fit
	altsigma:    	0.0       , $ ; altsigma of fit
	azcoeffs: 	fltarr( 4), $ ; fitted coeffs for az
	altcoeffs:	fltarr( 4), $ ; sig fitted coeffs for alt
	sigazcoeffs: 	fltarr( 4), $ ; sig fitted coeffs for az
	sigaltcoeffs:	fltarr( 4) $ ; sig fitted coeffs for alt
}, 2)

;DEFINE THE ARRAYS OF INPUT STRUCTURES...

restore, dirname+ outfile[ 0]

head_arr= replicate( head, nrfiles)
dat_arr= replicate( dat[0], 2, nrfiles)
fit_arr= replicate( fit[0], 2, nrfiles)

