;THIS FILE ILLUSTRATES HOW TO OBSERVE THE SUN FROM RISE TO SET.  THIS
;FILE IS INVOKED BEFORE THE SUN RISES; IT WAITS UNTIL THE ALTITUDE OF THE
;SUN EXCEEDS 15 DEGREES; AND RUNS UNTIL THE ALTITUDE DECREASES BELOW 15
;DEGREES. 

;ONE SHOULD ALSO HOME THE TELESCOPE EVERY HOUR OR SO...THOSE DAMNED
;INCREMENTAL ENCODERS!


;;INITIALIZE COMMON BLOCK...
;WE NOW DO THIS IN THE STARTUP FILE, SO NO NEED TO DO IT AGAIN.
;@common_init.idl
;

;;HOME THE DISH JUST TO MAKE SURE...
homer, woohoo=woohoo, doh=doh
;print, 'woohoo= ', woohoo
;print, 'doh= ', doh

retall

;THESE MUST BE COMPILED FIRST, SOME ARE FUNCTIONS CALLED BY OTHERS...
.run scan
.run correct
.run fx_root2
.run point2
.run dvm
.run spc

;THE OUTPUT DATA PATH, WHERE THE OUTPUTFILES ARE WRITTEN
datapath= '~heiles/ay121/data/'

;:FIND THE CURRENT ALTITUDE OF THE SUN. 
isun, altsun, azsun, /aa

;CALCULATE THE SUNS ALTITUDE EVERY 30 SEC; LEAVE THE LOOP WHEN SUN IS UP
while altsun lt 15. do begin &$
isun, altsun, azsun, /aa  &$
wait, 30. &$
endwhile

;HOME THE TELESCOPE
homer

;OBSERVE THE SUN REPETITIVELY UNTIL IT SETS
while altsun gt 15. do begin &$
isun, altsun, azsun, /aa  &$
print, '(altsun, azsun)= ', altsun, azsun &$
datafile= fname_time_gen() + '_scan.sav' &$
fname= datapath+ datafile &$
scan, fname, head, dat, size=10 &$
endwhile

