PRO DRIVE_RESET, IP_ADDR, PORT, MOVE_AXIS, VERBOSE=VERBOSE

ARG=STRING(13B)+STRING(13B)+MOVE_AXIS+'Z'+STRING(13B)
IF VERBOSE EQ 1 THEN PRINT, 'Resetting Drive ',MOVE_AXIS,', Please Wait.'
OEM_REPLY='12345'

WAIT,1

SOCKET,SOCK_UNIT,IP_ADDR,PORT,/GET_LUN
WRITEU,SOCK_UNIT,ARG
READU,SOCK_UNIT,OEM_REPLY
CLOSE,SOCK_UNIT
FREE_LUN,SOCK_UNIT

WAIT,.5
END
