PRO SET_HP, IP_ADDR, PORT, HP_ARG=HP_ARG, VERBOSE=VERBOSE

ARG=HP_ARG+STRING(13B)+STRING(10B)
IF VERBOSE EQ 1 THEN PRINT, 'Sending "',hp_arg,'" to HP Synthesizer'

WAIT,1

SOCKET,SOCK_UNIT,IP_ADDR,PORT,/GET_LUN
WRITEU,SOCK_UNIT,ARG
CLOSE,SOCK_UNIT
FREE_LUN, SOCK_UNIT


IF VERBOSE EQ 1 THEN PRINT, 'Success!'

END
