PRO SET_GO, IP_ADDR, PORT, VERBOSE=VERBOSE

ARG=STRING(13B)+STRING(13B)+'G'+STRING(13B)
IF VERBOSE EQ 1 THEN PRINT, 'Drive Going, Please Wait.'
OEM_REPLY='12345'

WAIT,1

SOCKET,SOCK_UNIT,IP_ADDR,PORT,/GET_LUN
WRITEU,SOCK_UNIT,ARG
CLOSE,SOCK_UNIT
FREE_LUN,SOCK_UNIT

END
